# Generated by Django 2.2.5 on 2020-01-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
