# Generated by Django 2.2.6 on 2020-02-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200225_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='mrp',
        ),
    ]
