# Generated by Django 2.2.6 on 2020-02-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200226_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='LBH',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
