# Generated by Django 2.2.6 on 2020-02-28 09:14

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=upload.models.upload_image_path)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
