# Generated by Django 2.2.6 on 2020-02-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
    ]
