# Generated by Django 2.2.6 on 2020-02-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Ordercount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
