# Generated by Django 2.2.6 on 2020-02-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
